main: me.gomeow.Depositchest
name: DespositChest
version: 1.0
website: www.dev.bukkit.org/server-mods/depositchest/
author: gomeow

commands:
  dc:
    description: Gives help to all DepositChest commands.

permissions:
  depositchest.*:
    description: All deposit chest permissions.
    children:
      depositchest.use: true
      depositchest.break: true
  depositchest.use:
    description: Able to set a deposit chest.
    default: true
  depositchest.break:
    description: Able to break other's deposit chests.
